version: '3.8'

services:
  backend:
    build: .
    container_name: spring_backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/product_review_db
      SPRING_DATASOURCE_USERNAME: review_user
      SPRING_DATASOURCE_PASSWORD: UTWsDpnLCRDPyqbghjSWjfW7K8cU6dMvVW7EgsRS
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - backend-network

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: product_review_db
      POSTGRES_USER: review_user
      POSTGRES_PASSWORD: UTWsDpnLCRDPyqbghjSWjfW7K8cU6dMvVW7EgsRS
    ports:
      - "5432:5432"
    networks:
      - backend-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  backend-network:

volumes:
  postgres-data:
