on:
  push:
    branches:
      - master  # Trigger when pushing to main

jobs:
  tag_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: ./mvnw clean package

      - name: Create Git Tag
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          git tag "v$VERSION"
          git push origin "v$VERSION"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ github.ref_name }}
          name: Release v${{ github.ref_name }}
          body: "Automated release of version v${{ github.ref_name }}"
          draft: false
          prerelease: false
          files: target/*.jar
